DROP TABLE IF EXISTS "materials";
DROP TABLE IF EXISTS "meeting_places";
DROP TABLE IF EXISTS "meetings";
DROP TABLE IF EXISTS "places";
DROP TABLE IF EXISTS "persons";
DROP TABLE IF EXISTS "users";
DROP TYPE IF EXISTS "role_type";